{{- if .Values.sqlserver.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "multi-cloud-demo.fullname" . }}-sqlserver
  labels:
    {{- include "multi-cloud-demo.labels" . | nindent 4 }}
    app.kubernetes.io/component: sqlserver
type: Opaque
data:
  sa-password: {{ .Values.sqlserver.auth.saPassword | b64enc }}
{{- end }}