apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "multi-cloud-demo.fullname" . }}-webapp-config
  labels:
    {{- include "multi-cloud-demo.labels" . | nindent 4 }}
    app.kubernetes.io/component: webapp
data:
  appsettings.json: |
{{ tpl (.Files.Get "config/webapp-appsettings.json") . | indent 4 }}