apiVersion: v2
name: multi-cloud-demo
description: A multi-cloud demo application with web app and background worker
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: redis
    version: "20.5.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled

maintainers:
  - name: Multi-Cloud Demo Team
    email: demo@example.com

keywords:
  - demo
  - multi-cloud
  - dotnet
  - redis
  - kubernetes