global:
  imageRegistry: ""
  imagePullSecrets: []

webapp:
  name: webapp
  image:
    repository: multi-cloud-demo/webapp
    tag: "2507"
    pullPolicy: IfNotPresent
  
  replicaCount: 1
  
  service:
    type: ClusterIP
    port: 80
    targetPort: 8080
  
  ingress:
    enabled: false
    className: ""
    annotations: {}
    hosts:
      - host: multi-cloud-demo.local
        paths:
          - path: /
            pathType: Prefix
    tls: []
  
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  
  readinessProbe:
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3
  
  env:
    - name: ASPNETCORE_ENVIRONMENT
      value: "Production"
    - name: ASPNETCORE_URLS
      value: "http://+:8080"

backgroundworker:
  name: backgroundworker
  image:
    repository: multi-cloud-demo/backgroundworker
    tag: "2507"
    pullPolicy: IfNotPresent
  
  replicaCount: 1
  
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 64Mi
  
  env:
    - name: DOTNET_ENVIRONMENT
      value: "Production"

redis:
  enabled: true
  auth:
    enabled: false
  master:
    persistence:
      enabled: false
  replica:
    replicaCount: 1
    persistence:
      enabled: false

sqlserver:
  enabled: true
  image:
    repository: mcr.microsoft.com/mssql/server
    tag: "2022-latest"
    pullPolicy: IfNotPresent
  
  service:
    type: ClusterIP
    port: 1433
  
  auth:
    saPassword: "YourStrong!Passw0rd"
  
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 8Gi
    storageClass: ""
  
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi
  
  startupProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 10
    failureThreshold: 12
  
  readinessProbe:
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3
  
  livenessProbe:
    initialDelaySeconds: 60
    periodSeconds: 60
    timeoutSeconds: 10
    failureThreshold: 5

nameOverride: ""
fullnameOverride: ""

logging:
  defaultLevel: "Warning"
  applicationLevel: "Information"

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 2000

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000

nodeSelector: {}

tolerations: []

affinity: {}

# StorageClass configuration (disabled by default)
storageClass:
  enabled: false
  name: ""
  provisioner: ""
  parameters: {}
  volumeBindingMode: "WaitForFirstConsumer"
  allowVolumeExpansion: true
  reclaimPolicy: "Delete"
  isDefault: false
  annotations: {}
  labels: {}