# values-eks.yaml - Amazon EKS environment configuration
# Usage: helm install demo . -f values-eks.yaml

webapp:
  replicaCount: 3
  
  service:
    type: LoadBalancer
    port: 80
    targetPort: 8080
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
  
  ingress:
    enabled: false  # Using LoadBalancer service instead
    className: "alb"
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
    hosts:
      - host: demo-eks.example.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: demo-eks-tls
        hosts:
          - demo-eks.example.com

backgroundworker:
  replicaCount: 5

sqlserver:
  enabled: true
  
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 100Gi
    storageClass: "gp3-storage-class"
  
  resources:
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 1000m
      memory: 2Gi

redis:
  enabled: true
  
  master:
    persistence:
      enabled: true
      size: 20Gi
      storageClass: "gp3-storage-class"
  replica:
    replicaCount: 2
    persistence:
      enabled: true
      size: 20Gi
      storageClass: "gp3-storage-class"

# AWS EKS specific settings
# nodeSelector removed - architecture is auto-detected by deployment scripts

# Environment-specific settings
logging:
  defaultLevel: "Information"
  applicationLevel: "Information"

# Pod security context for EKS
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 2000

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000

# EKS-specific StorageClass for GP3 volumes
storageClass:
  enabled: true
  name: "gp3-storage-class"
  provisioner: "ebs.csi.aws.com"
  parameters:
    type: "gp3"
    iops: "3000"
    throughput: "125"
    encrypted: "true"
    fsType: "ext4"
  volumeBindingMode: "WaitForFirstConsumer"
  allowVolumeExpansion: true
  reclaimPolicy: "Delete"
  isDefault: false
  annotations:
    storageclass.beta.kubernetes.io/provisioner: "ebs.csi.aws.com"
  labels:
    environment: "eks"
    storage-type: "gp3"